module OldView exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)


oldView : List (Html Msg)
oldView =
    [ h2 []
        [ text "chancesnow.me/party" ]
    , nav [ class "menu secondary", id "musicMenu" ]
        [ ul []
            [ li [ class "selected" ]
                [ a [ href "#nowPlaying" ]
                    [ text "Now Playing" ]
                ]
            , li []
                [ a [ href "#history" ]
                    [ text "History" ]
                ]
            , li [ id "upNextMenuItem" ]
                [ a [ href "#upNext" ]
                    [ text "Up Next" ]
                ]
            , li []
                [ a [ href "#contribute" ]
                    [ text "Contribute" ]
                ]
            ]
        ]
    , div [ attribute "data-show" "nowPlaying", id "content" ]
        [ div [ class "track", attribute "data-tab" "music", id "nowPlaying" ]
            [ h2 []
                [ text "Now Playing" ]
            , img [ src "https://ninjatune.net/images/releases/alium-main.jpg" ]
                []
            , div [ class "song-info" ]
                [ span [ class "title" ]
                    [ text "Worries" ]
                , span [ class "artist" ]
                    [ text "Submotion Orchestra" ]
                ]
            ]
        , div [ attribute "data-tab" "music", id "upNext" ]
            [ h2 []
                [ text "Up Next" ]
            , ul [ class "tracks" ]
                [ li [ class "track" ]
                    [ img [ src "https://ninjatune.net/images/releases/alium-main.jpg" ]
                        []
                    , div [ class "song-info" ]
                        [ span [ class "title" ]
                            [ text "Awakening" ]
                        , span [ class "artist" ]
                            [ text "Submotion Orchestra" ]
                        , span [ class "requested-by" ]
                            [ text "Added by Jake Perkins" ]
                        ]
                    ]
                , li [ class "track" ]
                    [ img [ src "https://i.scdn.co/image/671f5bc32e02cbca2568054b0f578e63b9e2fe31" ]
                        []
                    , div [ class "song-info" ]
                        [ span [ class "title" ]
                            [ text "Run" ]
                        , span [ class "artist" ]
                            [ text "Air" ]
                        , span [ class "requested-by" ]
                            [ text "Added by Bradley Rasmussen" ]
                        ]
                    ]
                , li [ class "track" ]
                    [ img [ src "https://upload.wikimedia.org/wikipedia/en/4/49/Bonobo_-_Black_Sands.jpg" ]
                        []
                    , div [ class "song-info" ]
                        [ span [ class "title" ]
                            [ text "Black Sands" ]
                        , span [ class "artist" ]
                            [ text "Bonobo" ]
                        ]
                    ]
                ]
            ]
        , div [ attribute "data-tab" "music", id "history" ]
            [ h2 []
                [ text "History" ]
            , ul [ class "tracks" ]
                [ li [ class "track" ]
                    [ img [ src "https://ninjatune.net/images/releases/alium-main.jpg" ]
                        []
                    , div [ class "song-info" ]
                        [ span [ class "title" ]
                            [ text "Awakening" ]
                        , span [ class "artist" ]
                            [ text "Submotion Orchestra" ]
                        , span [ class "requested-by" ]
                            [ text "Added by Jake Perkins" ]
                        ]
                    ]
                , li [ class "track" ]
                    [ img [ src "https://i.scdn.co/image/671f5bc32e02cbca2568054b0f578e63b9e2fe31" ]
                        []
                    , div [ class "song-info" ]
                        [ span [ class "title" ]
                            [ text "Run" ]
                        , span [ class "artist" ]
                            [ text "Air" ]
                        , span [ class "requested-by" ]
                            [ text "Added by Bradley Rasmussen" ]
                        ]
                    ]
                , li [ class "track" ]
                    [ img [ src "https://f4.bcbits.com/img/a1394314813_16.jpg" ]
                        []
                    , div [ class "song-info" ]
                        [ span [ class "title" ]
                            [ text "Ellliptic" ]
                        , span [ class "artist" ]
                            [ text "Vessels" ]
                        ]
                    ]
                , li [ class "track" ]
                    [ img [ src "https://upload.wikimedia.org/wikipedia/en/4/49/Bonobo_-_Black_Sands.jpg" ]
                        []
                    , div [ class "song-info" ]
                        [ span [ class "title" ]
                            [ text "Black Sands" ]
                        , span [ class "artist" ]
                            [ text "Bonobo" ]
                        ]
                    ]
                ]
            ]
        , div [ attribute "data-tab" "music", id "contribute" ]
            [ form []
                [ input [ attribute "autocomplete" "off", id "query", name "q", placeholder "Search for a song", attribute "required" "", type' "text" ]
                    []
                , text "      "
                , input [ type' "reset", value "×" ]
                    []
                , text "    "
                ]
            , div [ id "results" ]
                [ ul [ class "tracks" ]
                    []
                ]
            ]
        ]
    , nav [ class "menu", id "mainMenu" ]
        [ ul []
            [ li [ class "selected" ]
                [ a [ href "#music" ]
                    [ text "Music" ]
                ]
            , li []
                [ a [ href "#guests" ]
                    [ text "Guests" ]
                ]
            ]
        ]
    ]
